// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "7bb094ba-7262-4cc8-b8ed-53f650195218");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567693643);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567693763);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567743623);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1567747343);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567747223);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1567693523);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1567693163);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567693883);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 15081);
user_pref("browser.cache.disk.capacity", 245760);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1563950839);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0e965b15-74d1-47bd-ad39-13808c04ce60}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1567749108684");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1567750926684");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1567747246132");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1567750846132");
user_pref("browser.search.region", "KR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190828152820");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1567743622");
user_pref("browser.slowStartup.averageTime", 45948);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190828152820");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1567743613);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1563950852571");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "084221fdc03b440c8f8cbd29fce4f1b7");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 28 Aug 2019 19:55:12 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1567693644);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190828152820");
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"bdb21870-fa67-4cf8-bcd0-73463ef59e4f\",\"fxmonitor@mozilla.org\":\"06f6d180-23af-4a02-891d-57cb79128f9f\",\"screenshots@mozilla.org\":\"121c16a1-1342-4f2c-adeb-6017468b75d0\",\"webcompat-reporter@mozilla.org\":\"b64333ff-27a3-408d-bff7-300086176ecc\",\"webcompat@mozilla.org\":\"91e2b9e8-210f-4ddd-89db-523aaf8184c2\",\"default-theme@mozilla.org\":\"5a6e4b66-2199-410b-aa91-d5adf8e89e7d\",\"google@search.mozilla.org\":\"7ab79f0c-b1fb-450c-8453-8c7a669e530f\",\"amazondotcom@search.mozilla.org\":\"e933177c-2028-4a85-8cd9-036856f16fb5\",\"bing@search.mozilla.org\":\"59423ce7-1843-4131-84b0-2775030ba1d1\",\"ddg@search.mozilla.org\":\"d43e6679-a6db-4710-bb26-7cf101d81949\",\"ebay@search.mozilla.org\":\"1a563eef-1fe8-40ad-9a67-14625bfd1342\",\"twitter@search.mozilla.org\":\"337c086c-6c6c-43e5-837d-8fb759e85de6\",\"wikipedia@search.mozilla.org\":\"3794b080-4c4f-46d6-be2d-116f9e63ae31\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("idle.lastDailyNotification", 1567743938);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1563950913);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190828152820");
user_pref("media.gmp-manager.lastCheck", 1567693266);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1567743939);
user_pref("places.history.expiration.transient_current_max_pages", 51048);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "023c9127-d4b4-4bbd-930b-2fce138da2c4");
user_pref("security.sandbox.plugin.tempDirSuffix", "f0cde474-8e9b-4d13-a0e4-82329f8fbcaa");
user_pref("services.blocklist.pinning.checked", 1567693523);
user_pref("services.settings.clock_skew_seconds", -84);
user_pref("services.settings.last_etag", "\"1567711579212\"");
user_pref("services.settings.last_update_seconds", 1567743711);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1567743711);
user_pref("services.settings.main.cfr-fxa.last_check", 1567743711);
user_pref("services.settings.main.cfr.last_check", 1567743711);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1567743711);
user_pref("services.settings.main.hijack-blocklists.last_check", 1567743711);
user_pref("services.settings.main.language-dictionaries.last_check", 1567743711);
user_pref("services.settings.main.normandy-recipes.last_check", 1567743711);
user_pref("services.settings.main.onboarding.last_check", 1563951461);
user_pref("services.settings.main.sites-classification.last_check", 1567743711);
user_pref("services.settings.main.tippytop.last_check", 1567743711);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1567743711);
user_pref("services.settings.security.onecrl.checked", 1567693523);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1567743939);
user_pref("toolkit.startup.last_success", 1567743511);
user_pref("toolkit.telemetry.cachedClientID", "504ba76f-7a71-41ae-89bb-08baba052e11");
user_pref("toolkit.telemetry.previousBuildID", "20190828152820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
